version: '3'
services:
    rabbitmq:
        image: rabbitmq:3
        ports:
            - "5672:5672"
        restart: on-failure
    message_queue:
        build: .
        command: python aiohttp_test/message_queue_worker.py
        depends_on:
            - rabbitmq
        restart: on-failure
        deploy:
            replicas: 2
    api_server:
        build: .
        command: python aiohttp_test/api_server_worker.py --sites 2
        depends_on:
            - message_queue
        ports:
            - "8081:8081"
            - "8082:8082"
        restart: on-failure
    socket_server:
        build: .
        command: python aiohttp_test/socket_server_worker.py
        ports:
            - "8181:8181"
        restart: on-failure